name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jawaadw/carta:latest
    - name: Run Tests & Serve
      run: >
           docker run jawaadw/carta 
           sh -c 
           "sed -i 's/<h1>Hi<\/h1>/<h1>Jawaad Waheed<\/h1><h2>jawaadw@gmail.com<\/h2><h3><a href=\"https:\/\/github.com\/jawaadw\/CartaTest\/actions\">Link to DockerHub Repo<\/a><\/h3>/g' app/templates/index.html 
           && carta-devops test"
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: jawaadw
        password: ac5b96e2-2d0e-4058-9dd5-47942d6899ca
    - name: Publish to Dockerhub
      run: docker push jawaadw/carta:latest
