name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jawaadw/carta:latest
    - name: Run Tests & Add Name to File
      run: docker run jawaadw/carta:latest carta-devops test
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: jawaadw
        password: 387b455e-87e3-4dc9-bded-5004cdceadb5 # This is an old access token; It doesn't work anymore
    - name: Publish to Dockerhub
      run: docker push jawaadw/carta:latest
